### ISSUE TITLE
Show chapters from comment timestamps

### ISSUE THREAD

**Issue by ris58h** [ris58h/youtube-chapters-in-player#19]
@Lazyt3ch suggested to show chapters from comment timestamps.
There is a video without chapters but with timestamps in the comments https://www.youtube.com/watch?v=l-joOy1Y2SI .
Seems like we should show chapters from a pinned comment just to be sure.

**Comment by Lazyt3ch** [comment]
Hi,
I'd like to create a PR related to this issue from a fork of your project.

**Comment by ris58h** [comment]
ok

**Comment by ris58h** [comment]
@Lazyt3ch we need to discuss what comments we consider as chapters comments.

Let's start with your video example https://www.youtube.com/watch?v=l-joOy1Y2SI
The comment that contains chapters:
- is pinned
- has more than one timestamp
- timestamps are in the beginning of the line
- timestamps are in ascending time order
- timestamps are less than video duration

Probably we don't need all that requirements to identify chapters comments but it's a good start. What do you think?

**Comment by Lazyt3ch** [comment]
> @Lazyt3ch we need to discuss what comments we consider as chapters comments.
> 
> Let's start with your video example https://www.youtube.com/watch?v=l-joOy1Y2SI The comment that contains chapters:
> 
> * is pinned
> * has more than one timestamp
> * timestamps are in the beginning of the line
> * timestamps are in ascending time order
> * timestamps are less than video duration
> 
> Probably we don't need all that requirements to identify chapters comment but it's a good start. What do you think?

Actually, all of these suggestions are good. However, chapter comments are a rare thing, so I believe we could just use the top pinned comment if it contains timestamps-like text.

**Comment by ris58h** [comment]
@Lazyt3ch version 0.3.0 with your fix is available in [Chrome Web Store](https://chrome.google.com/webstore/detail/youtube-chapters-in-playe/ikalbbakholajifblhnmbcffhmhnnohl).

**Comment by Lazyt3ch** [comment]
> @Lazyt3ch version 0.3.0 with your fix is available in [Chrome Web Store](https://chrome.google.com/webstore/detail/youtube-chapters-in-playe/ikalbbakholajifblhnmbcffhmhnnohl).

@ris58h Great, thanks for info.
