### ISSUE TITLE
Multiple chapters with the same timestamp are not displayed in chapter menu

### ISSUE THREAD

**Issue by scholtzm** [ris58h/youtube-chapters-in-player#23]
Example video:
https://www.youtube.com/watch?v=Ra5eagzDQiw

Description:
![obrázok](https://github.com/ris58h/youtube-chapters-in-player/assets/2640934/61d3bcb5-b6bd-412f-aa5c-32767fd3c26b)

Chapter menu:
![obrázok](https://github.com/ris58h/youtube-chapters-in-player/assets/2640934/77000536-a8d0-4e8a-90e7-e02b3f32ad74)

Chapters 8 and 10 are omitted by the extension.

**Comment by ris58h** [comment]
The extension shows chapters that video has, not that mentioned in the description. You can find them right after the description at the bottom of the details section.

<img width="803" alt="Screenshot 2023-10-17 at 22 55 10" src="https://github.com/ris58h/youtube-chapters-in-player/assets/511242/a219f165-2594-4041-9234-abf652734d8f">

As you can see there is no the 10th chapter. I don't know if it's a mistake of the author or YouTube.

**Comment by scholtzm** [comment]
I see now.

I'm not sure where chapter info comes from -- whether YT just parses the description or author needs to add these chapters somewhere in video settings. Either way, I see this is out of scope for this extension. Thanks for the info.
